version: 2

models:
  - name: stage_pro_wrestling_events
    description: >
      Staging table for raw pro wrestling events extracted from cagematch.net, 
      filtered for dates after 2021-01-01 and event types TV-Show, Pay Per View, or Premium Live Event.
    columns:
      - name: calendar_date
        description: Event date (parsed from raw date string)
        tests:
          - not_null

      - name: promotion
        description: >
          Promotion or brand for the event. Standardized to AEW if AEW or NJPW is present in the brand list.
        tests:
          - not_null

      - name: event_name
        description: >
          Clean event name, stripped of brands, show numbers, and extraneous tags.
        tests:
          - not_null

      - name: event_type
        description: Type of event (TV-Show, Pay Per View, Premium Live Event)
        tests:
          - accepted_values:
              values: ['TV-Show', 'Pay Per View', 'Premium Live Event']

      - name: event_show_name
        description: >
          Show name or subtitle if present (e.g., 'Night 1', 'Saturday'), otherwise null.

      - name: event_show_number
        description: Show number extracted from event name, if present.

      - name: event_arena_name
        description: Name of the arena where the event took place.

      - name: event_city
        description: City where the event was held.

      - name: event_state
        description: State or province where the event was held.

      - name: event_country
        description: Country where the event was held.

      - name: event_broadcast_type
        description: Broadcast type for the event (e.g., PPV, TV, PLE).

      - name: event_broadcast_network
        description: Broadcast network for the event.

      - name: event_attendance
        description: Event attendance (cleaned and cast as integer).

      - name: event_name_original
        description: Original event name from the raw data.

      - name: event_location_original
        description: Original location string from the raw data.

  - name: dim_event
    description: >
      Dimension table for unique wrestling events, generated from the stage_pro_wrestling_events model.
      Uses a surrogate key for uniqueness and joins.
    columns:
      - name: dim_event_key
        description: >
          Surrogate key for the event, generated using dbt_utils.generate_surrogate_key on:
          promotion, event_name, event_type, event_show_name, event_show_number,
          event_broadcast_type, event_broadcast_network, calendar_date.
        tests:
          - unique
          - not_null

      - name: calendar_date
        description: Event date.

      - name: promotion
        description: Promotion or brand for the event.

      - name: event_name
        description: Clean event name.

      - name: event_type
        description: Event type (TV-Show, Pay Per View, Premium Live Event).

      - name: event_show_name
        description: Show name or subtitle if present.

      - name: event_show_number
        description: Show number extracted from event name, if present.

      - name: event_broadcast_type
        description: Broadcast type for the event.

      - name: event_broadcast_network
        description: Broadcast network for the event.

  - name: dim_match
    description: >
      Dimension table for unique wrestling matches, generated from the stage_pro_wrestling_matches model.
      Uses a surrogate key for uniqueness and joins to dim_event.
    columns:
      - name: dim_match_key
        description: >
          Surrogate key for the match, generated using dbt_utils.generate_surrogate_key on:
          calendar_date, promotion, event_name, event_type, event_show_number, event_show_name,
          match_type, match_winner, match_loser, match_ended_by, match_duration_seconds, match_title_change.
        tests:
          - unique
          - not_null

      - name: calendar_date
        description: Event date.

      - name: promotion
        description: Promotion or brand for the event.

      - name: event_name
        description: Clean event name.

      - name: event_type
        description: Event type (TV-Show, Pay Per View, Premium Live Event).

      - name: event_show_number
        description: Show number extracted from event name, if present.

      - name: event_show_name
        description: Show name or subtitle if present.

      - name: event_arena_name
        description: Name of the arena where the event took place.

      - name: match_type
        description: Type or stipulation of the match.

      - name: match_winner
        description: Winner(s) of the match.

      - name: match_loser
        description: Loser(s) of the match.

      - name: match_ended_by
        description: Method by which the match ended (e.g., pinfall, submission).

      - name: match_duration_seconds
        description: Match duration in seconds.

      - name: match_time_limit
        description: Time limit for the match, if specified.

      - name: match_title_change
        description: Boolean indicating if a title changed hands.

      - name: dim_event_key
        description: Foreign key to the dim_event table.

  - name: dim_location
    description: >
      Dimension table for unique event locations, generated from the stage_pro_wrestling_events model.
      Uses a surrogate key for uniqueness and joins.
    columns:
      - name: dim_location_key
        description: >
          Surrogate key for the location, generated using dbt_utils.generate_surrogate_key on:
          event_city, event_state, event_country.
        tests:
          - unique
          - not_null

      - name: event_city
        description: City where the event was held.

      - name: event_state
        description: State or province where the event was held.

      - name: event_country
        description: Country where the event was held.

  - name: dim_date
    description: >
      Date dimension table generated from unique calendar dates in stage_pro_wrestling_events.
      Provides standard calendar attributes for joining and reporting.
    columns:
      - name: dim_date_key
        description: >
          Surrogate key for the date, formatted as yyyymmdd integer (e.g., 20240612).
        tests:
          - unique
          - not_null

      - name: calendar_date
        description: Calendar date in DATE format.
        tests:
          - unique
          - not_null

      - name: calendar_year
        description: Four-digit year extracted from calendar_date.

      - name: day_name
        description: Name of the day of week (e.g., 'Monday').

      - name: month_name
        description: Name of the month (e.g., 'January').

      - name: calendar_quarter
        description: Calendar quarter (1-4).

      - name: week_of_year
        description: ISO week number of the year.

      - name: day_of_year
        description: Day of the year (1-366).

      - name: is_weekend
        description: Boolean indicating if the date is a Saturday or Sunday.

  - name: dim_arena
    description: >
      Dimension table for unique arenas, generated from the stage_pro_wrestling_events model.
      Uses a surrogate key for uniqueness and joins.
    columns:
      - name: dim_arena_key
        description: >
          Surrogate key for the arena, generated using dbt_utils.generate_surrogate_key on event_arena_name.
        tests:
          - unique
          - not_null

      - name: event_arena_name
        description: Name of the arena where the event took place.
        tests:
          - not_null

  - name: report_pro_wrestling_events
    description: >
      Reporting model joining match-level and event-level data for pro wrestling analytics.
      Combines dimensions, fact tables, and attendance for use in BI tools and dashboards.
    columns:
      - name: calendar_date
        description: Event date.

      - name: promotion
        description: Name of promotion.

      - name: event_name
        description: Name of the event.

      - name: event_type
        description: Type of event (TV-Show, Pay Per View, Premium Live Event).

      - name: event_show_name
        description: Show name or subtitle if present.

      - name: event_show_number
        description: Show number extracted from event name, if present.

      - name: event_broadcast_type
        description: Broadcast type for the event (e.g., PPV, TV, PLE).

      - name: event_broadcast_network
        description: Broadcast network for the event.

      - name: event_arena_name
        description: Name of the arena where the event took place.

      - name: event_city
        description: City where the event was held.

      - name: event_state
        description: State or province where the event was held.

      - name: event_country
        description: Country where the event was held.

      - name: match_type
        description: Type or stipulation of the match.

      - name: is_match_stipulation
        description: Flags if a match has a stipulation (ie ladder match).

      - name: is_title_match
        description: Flags if the match is a title match.

      - name: match_winner
        description: Winner(s) of the match.

      - name: match_loser
        description: Loser(s) of the match.

      - name: match_ended_by
        description: Method by which the match ended (e.g., pinfall, submission).

      - name: match_time_limit
        description: Time limit for the match, if specified.

      - name: match_title_change
        description: Boolean indicating if a title changed hands.

      - name: match_duration_seconds
        description: Match duration in seconds.

      - name: event_attendance
        description: >
          Attendance for the event, sourced from event-level fact table.

